import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Avatar from 'components/Avatar'
import {MagnifyingGlassIcon,MicrophoneIcon,Squares2X2Icon} from '@heroicons/react/24/solid'
import Footer from 'components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter()
  const searchInputRef= useRef(null)

  const search = (e)=>{
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;
    router.push(`/search?term=${term}`)
  }

  return(
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google Clone 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1 className='flex'>
        This is a demo text to ensure the code is working</h1> */}
    {/* Header */}
    <header className='flex w-full p-5 justify-between text-sm text-gray-700' >
      <div className='flex space-x-4 items-center'>
      <p className='link'>About</p>
      <p className='link'>Store</p>
      </div>
      <div className='flex space-x-4 items-center'>
      <p className='link'>Gmail</p>
      <p className='link'>Images</p>
      {/* icon */}
      <Squares2X2Icon className='transform h-8 p-1 rounded-full hover:bg-gray-100 hover:transition cursor-pointer duration-150 scale-110'/>


      {/* Avatar */}
      <Avatar url="https://avatars.githubusercontent.com/u/101728177?v=4"/>
      </div>
    </header>
    {/* body */}
    <form className='flex flex-col items-center margin mt-18 flex-grow w-4/5'>
      <Image
      src='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
      width={300}
      height={100}
      />
      <div className='rounded-full border border-gray-200 px-5 py-3 items-center flex w-full mt-5 hover:shadow-lg max focus-within:shadow-lg max-w-md sm:max-w-xl lg:max-w-2xl'>
        <MagnifyingGlassIcon className='h-5 mr-3 text-gray-500'/>
        <input ref={searchInputRef} type='text'
        className='focus:outline-none flex-grow'
        />
        <MicrophoneIcon className='h-5 ml-3 text-gray-500'/>
      </div>
      <div className='flex flex-row  justify-center mt-8 sm:flex-row sm:space-x-4'>
        <button onClick={search} className='btn'>Google Search </button>
        <button onClick={search} className='btn'>I'm Feeling Lucky</button>
      </div>
    </form>
    {/* footer */}
    <Footer/>
    </div>
  )
}